### ISSUE TITLE
Remove VIB logo

### ISSUE THREAD

**Issue by rabuono** [FAIRdom/fairdom.github.io#23]
Please remove the VIB logo from https://fairdom.github.io/partners.html
Only the ELIXIR-Belgium logo should be there.

**Comment by smza** [comment]
> Please remove the VIB logo from https://fairdom.github.io/partners.html
> Only the ELIXIR-Belgium logo should be there.

Done.

**Comment by floradanna** [comment]
@smza I can still see it on the website.

**Comment by smza** [comment]
> @smza I can still see it on the website.

There was some problem with the Git the site was not getting build. Now done!
