### ISSUE TITLE
Data Management Checklist

### ISSUE THREAD

**Issue by alaninmcr** [FAIRdom/fairdom.github.io#41]
This probably needs updating. Need to look at DMP standards

**Comment by smza** [comment]
This needs work and will need to updated by  @wittigue @korbinib @floradanna  and others.

**Comment by floradanna** [comment]
Can't we link to the FAIR principles paper and go fair (https://www.go-fair.org/fair-principles/) and RDMkit ?

**Comment by korbinib** [comment]
Good idea. We could orient on this: https://scienceeurope.org/media/411km040/se-rdm-template-3-researcher-guidance-for-data-management-plans.docx (which is based on https://scienceeurope.org/our-resources/practical-guide-to-the-international-alignment-of-research-data-management/ | https://doi.org/10.5281/zenodo.4915861) and point to the usual suspect tools? We should try not to replicate https://rdmkit.elixir-europe.org/data_management_plan.html

**Comment by floradanna** [comment]
I was actually proposing something very minimal, like giving a more generic title to the page, such as "**Data management**" and then writing something like:

" Good data management consists in making research data Findable, Accessible, Interoperable and Reusable (FAIR), as much as possible.

**What’s FAIR?**
The FAIR principles have been formalised in the publication “The FAIR Guiding Principles for scientific data management and stewardship”. The FAIR principles ‘living document’ is now hosted and maintained at https://www.go-fair.org/fair-principles/.

**Practical information for data management**
Every funder, university and research institute usually provide information about data management requirements and best practices. Therefore, it is recommended to be aware of the guidelines provided by your funder, university or research institute.

Generic data management best practices and guidelines can be found in [RDMkit](https://rdmkit.elixir-europe.org). "

**Comment by wittigue** [comment]
Great idea @floradanna! I prefer that.

**Comment by korbinib** [comment]
Started a PR #48 based on this discussion. - Please edit accordingly. What should the title be? Data management? Data management requirements?
