### ISSUE TITLE
Issue on page: Contact Us

### ISSUE THREAD

**Issue by wittigue** [FAIRdom/fairdom.github.io#60]
I would like to report an issue on the Contact Us page at `/contact`. Description of the issue:

There is a problem with the contact email address which is just shown as **

**Comment by smza** [comment]
@bedroesb  and @stuzart do we need to use this format: **{{ site.contact_email }}**? Could you please check what is causing the error?

**Comment by bedroesb** [comment]
ooh good catch! the theme does not make use of this variable anymore, I will will fix it in the page

**Comment by bedroesb** [comment]
Should be fixed now

**Comment by smza** [comment]
Thanks @bedroesb. Its sorted. I'll close the issue.
