### ISSUE TITLE
Public mailing list

### ISSUE THREAD

**Issue by floradanna** [FAIRdom/fairdom.github.io#65]
FAIRDOM self-subscribing mailing list - fairdom@listserv.manchester.ac.uk

Should the link to self-subscribe to this mailing list be provided on the website or not? Should we only give it to people that contact us via other emails first or during users meeting?

**Comment by stuzart** [comment]
It's provided on the website at https://fair-dom.org/get_involved

**Comment by floradanna** [comment]
ok. thanks
