### ISSUE TITLE
German Federal Ministry of Education and Research (BMBF) funder logo

### ISSUE THREAD

**Issue by PhilReedData** [FAIRdom/fairdom.github.io#88]
Hello @OlgaKrebs, please could you provide me the logo for German Federal Ministry of Education and Research (BMBF) for the [Funders](https://github.com/FAIRdom/fairdom.github.io/blob/master/pages/about/funders.md) page? How would you like me to represent them? Many thanks.

**Comment by OlgaKrebs** [comment]
ry for late response , dear Phill - I was travelling last 2 weeks - but here it is :-)
![imageBMBF](https://github.com/user-attachments/assets/1e69e2ef-fad1-4862-932f-85a8b18acf94)
